[pytest]
addopts = -p no:warnings
filterwarnings =
    ignore::DeprecationWarning:_pytest.*: 
    ignore::DeprecationWarning:werkzeug.*:
    ignore:ast.Str is deprecated:ast:
    ignore:Attribute s is deprecated:ast:
